---

# administrate databases and users

- name: administrate mysql databases
  mysql_db:
    name:           "{{ item.name }}"
    collation:      "{{ item.collation | default('utf8_general_ci') }}"
    encoding:       "{{ item.encoding | default('utf8') }}"
    state:          "{{ item.state | default('present') }}"
    login_user:     "root"
    login_password: "{{ mysql_root_password }}"
  with_items: "{{ mysql_databases }}"

- name: administrate mysql users
  mysql_user:
    name:           "{{ item.name }}"
    password:       "{{ item.pass | default('') }}"
    priv:           "{{ item.priv | default('*.*:ALL') }}"
    host:           "{{ item.host | default('localhost') }}"
    state:          "{{ item.state | default('present') }}"
    login_user:     "root"
    login_password: "{{ mysql_root_password }}"
  with_items: "{{ mysql_users }}"
